### ISSUE TITLE
Development setting up issue

### ISSUE THREAD

**Issue by erusseil** [light-curve/light-curve-feature#120]
Crash encounter when following the instructions for setting up from the README.
After rustup installation.

git clone --recursive https://github.com/light-curve/light-curve-feature
cd light-curve-feature
cargo test

Result in the following crash
![image](https://github.com/light-curve/light-curve-feature/assets/79919110/bf406b08-4117-4f4c-9ee9-3cb07f30aaae)

**Comment by hombit** [comment]
I've updated readme in #121
