### ISSUE TITLE
How were bounds for VillarFit chosen?

### ISSUE THREAD

**Issue by gnarayan** [light-curve/light-curve-feature#23]
Looking at @SammyS15's work using the Villar Fits on the ZTF/YSE dataset, some of the fits to objects with large amounts of data have very unphysical features. This seems to me to be because the fit params are going out of reasonable bounds. Bounds are set in this call - how were these values chosen?

https://github.com/light-curve/light-curve/blob/cbfd10258b69a5d898add24932d1e8b1a0f01e9f/light-curve-feature/src/features/villar_fit.rs#L154

**Comment by hombit** [comment]
I close this issue while custom initial guesses, boundary conditions and priors (last two work for MCMC only) are implemented in both Rust and Python packages.
